- src/driver/linux_onload/linux_stats.c
- src/driver/linux_resource/bt_stats.c
- src/driver/linux_resource/filter.c
- src/driver/linux_resource/kernel_compat.sh
- src/driver/linux_resource/kernel_proc.c
- src/include/ci/driver/kernel_compat.h
- src/lib/efthrm/tcp_helper_resource.c
Fix for the #82 
Checked by rebuilding gnu and modules on "old" and "new" kernels. Both are ok.
- "old" CentOS Stream 9 (5.14.0-80.el9.x86_64) `mmakebuildtree --gnu; make -C build/gnu_x86_64/ -j4; mmakebuildtree --driver; make -C build/x86_64_linux-5.14.0-80.el9.x86_64/`
- "new" CentOS Stream 9 (5.14.0-124.el9.x86_64) `mmakebuildtree --gnu; make -C build/gnu_x86_64/ -j4; mmakebuildtree --driver; make -C build/x86_64_linux-5.14.0-124.el9.x86_64/ -j4`
> Centos9 5.14.0-124 drivers build fix

- scripts/onload_misc/openonload.spec
Fixes #89 
As specified in [Packaging-Guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_syntax) there should be a test wether it's a full-blown install/uninstall, or if it's a package upgrade.
I only added it on the post-uninstall sequence, as we still want to have the latest version of `/usr/share/onload/onload_modules-load.d.conf` to be propagated on the copied (untracked) file.
> issue #89: fix onload module file being removed during upgrades

- Makefile
- mk/linux_kbuild.mk
- mk/site/mmake.mk
- scripts/onload_install
- src/driver/linux_resource/mmake.mk
- src/driver/linux_resource/resource_driver.c
- src/driver/mmake.mk
- src/include/ci/efhw/af_xdp.h
- src/lib/efhw/nic.c
- src/lib/efrm/efrm_pio.c
- src/lib/efrm/efrm_slice_ext.c
Introduce the HAVE_SFC variable to control sfc/driverlink build.
If it is unset (default), disable build of the entire netdriver
and driverlink support, and also other code in sfc_resource module
which uses driverlink API:
- PIO support
- EF100 slice extensions support
It is useful to isolate netdriver and onload modules build to get an easier
way to add support of new kernel versions in case when sfc build is broken
on new kernels (5.18 for now). For AF_XDP we do not need sfc and driverlink,
so we may proceed with new kernel support avoiding netdriver issues.
---
**Testing done**
Onload works with Debian 5.18.0-2-amd64 in AF_XDP mode when building with `MMAKE_LIBERAL=1`. (despite a lot of warnings when building modules).
> implement capability to disable netdriver build

- src/driver/linux_resource/kernel_proc.c
- src/include/ci/compat/utils.h
- src/lib/efthrm/tcp_helper_endpoint_move.c
- src/lib/transport/ip/netif_tx.c
- src/lib/transport/ip/netif_tx.h
- src/lib/transport/ip/socket.c
- src/lib/transport/ip/tcp_init_shared.c
- src/lib/transport/ip/udp.c
Fix compiler warnings appearing on 5.18 kernel.
See #95 
**Testing done:**
build drivers on Debian 5.18.0-4-amd64 with GCC 12.2.0.
`make -C build/x86_64_linux-5.18.0-4-amd64/ -j4 HAVE_SFC=0`
Socket Tester sanity all pass (was run on  Debian11 5.18.0-0.deb11.3-rt-amd64)
> Fix 5.18 warnings

- scripts/onload_build
- scripts/onload_install
Improve `onload_build` and `onload_install` scripts for non-sfc case - make them more convenient for a user.
---
**Testing**
System: Debian 5.18.0-4-amd64
Command line:
```shell
$ sudo ./scripts/onload_install --no-sfc
onload_install: Building Onload without sfc driver
onload_install: Building Onload.
....
$ sudo onload_tool reload --onload-only                                                                                           
onload_tool: /sbin/modprobe onload                                                                                                                                                                                 
$ lsmod | grep sfc
sfc_char              131072  1 onload
sfc_resource          159744  2 onload,sfc_char
```
> Improve build/install scripts for non-sfc case

- src/lib/efhw/af_xdp.c
In Linux 5.19 the `bpf_op_t` is moved into private code and it is not available for modules anymore.
See kernel commit 6264f58ca0e54e41d63c2d00334a48bac28fbf30 which introduces the breakage.
---
Tested by building modules on CentOS 8  with kernels:
- 5.19.1-1.el8.elrepo.x86_64
- 5.16.13-1.el8.elrepo.x86_64
Both are ok.
> issue #95: af_xdp: remove use of bpf_op_t

- src/include/onload/version.h
- src/lib/cplane/onload_version.c
- src/lib/transport/unix/startup.c
When the library is run as an executable, new gcc-12 results in segfault. Simplify the code in onload_version_msg(), so that it works seamlessly.
Avoid local_strlen(), because it results in strlen() call in any way (when using gcc-12).
Additionally, msg0 was not initialized properly with gcc-12, and I failed to understand why.  Given that local_strlen() is harmful now, I did not explore it further.
-------
**Tested** on Debian testing with gcc-12.
before the patch:
```
bash$ $ONLOAD_PRELOAD 
Segmentation fault (core dumped)
```
after the patch:
```
bash$ $ONLOAD_PRELOAD 
Onload 79181116e7 2022-10-06 segfault-gcc-12 
Copyright 2019-2022 Xilinx, 2006-2019 Solarflare Communications, 2002-2005 Level 5 Networks
Built: Oct  6 2022 16:10:19 (debug)
Build profile header: …
```
> gcc-12: fix segfault when executing library

- Makefile
ciul library depends on autocompat.h, and Makefile should know it.
----
Fixes #110
> newdriver build: fix -j option for ciul library

- src/driver/linux_resource/kernel_compat.sh
- src/lib/efthrm/tcp_helper_linux.c
Fix `struct iov_iter` processing in `f_ops->read_iter()` handler.
New 6.0 Linux changed the way it initializes `struct iov_iter` when passing it to read_iter().
**Testing**:
Onload build passes on CentOS 8: kernels `6.0.7-1.el8.elrepo.x86_64` and `4.18.0-408.el8.x86_64` both DEBUG and NDEBUG
Run socket tester test which calls read() from libc:
`--ool=socket_cache --ool=onload --tester-run=sockapi-ts/level5/fd_caching/fd_cache_nonblock_sync:env=VAR.env.peer2peer_two_iut,check_first=FALSE,nonblock_first=TRUE,nonblock_func=fcntl,func=read`
The test is green.
Before the patch it failed with ci_assert on 6.0:
```
[  629.748359] [onload] FAIL at /var/tmp/dnman/onload/src/include/ci/tools/iovec.h:34
[  629.756430] [onload] ci_assert(iovlen > 0)
[  629.756430] from …
```
> Compat for Linux 6.0

- Makefile
Do not try to create symlink for a module that was not built.
Fixes: f428e7470189 ("implement capability to disable netdriver build")
---
Building with sfc:
```
$ mmakebuildtree --newdriver
$ make -j4 -C build/x86_64_linux-5.10.0-19-amd64/
$ ls -l build/x86_64_linux-5.10.0-19-amd64/driver/linux/
total 40
-rwxr-xr-x 1 nikitins oktetlabs 20994 Nov 23 19:20 load.sh
lrwxrwxrwx 1 nikitins oktetlabs    39 Nov 23 19:20 onload.ko -> ../../src/driver/linux_onload/onload.ko
lrwxrwxrwx 1 nikitins oktetlabs    39 Nov 23 19:20 sfc_char.ko -> ../../src/driver/linux_char/sfc_char.ko
lrwxrwxrwx 1 nikitins oktetlabs    69 Nov 23 19:20 sfc_driverlink.ko -> ../../src/driver/linux_net/drivers/net/ethernet/sfc/sfc_driverlink.ko
lrwxrwxrwx 1 nikitins oktetlabs    58 Nov 23 19:20 sfc.ko -> …
```
> makefile: fix --newdriver build with HAVE_SFC=0

- mk/platform/linux.mk
- src/lib/citools/mmake.mk
- src/lib/ciul/mmake.mk
- src/lib/cplane/mmake.mk
- src/lib/transport/ip/mmake.mk
The fix for #114 
---
Testing:
Build on Debian11 with `6.1.0-rc3` passes.
```
mmakebuildtree --driver && make -C build/x86_64_linux-6.1.0-rc3/ HAVE_SFC=0 
```
Run Socket Tester `usecases/send_recv` test. All iterations pass.
> Fix modules build on Linux 6.1 

- README.md
- mk/linux_kbuild.mk
- scripts/mmakebuildtree
- src/lib/efhw/af_xdp.c
- src/tools/bpf_link_helper/Makefile
- src/tools/bpf_link_helper/bpf-link-helper.c
Checked on raspberry-pi:
- Debian11
- kernel 5.4.83
- `bcmgenet` ethernet driver
Loading:
```bash
onload_build --kernel --user64 --no-sfc
sudo onload_install --nobuild --no-initramfs --no-sfc
sudo onload_tool reload --onload-only
make -C ~/onload/src/tools/bpf_link_helper/
echo ~/onload/src/tools/bpf_link_helper/bpf-link-helper | sudo tee /sys/module/sfc_resource/parameters/bpf_link_helper
echo eth1 | sudo tee /sys/module/sfc_resource/afxdp/register
[325417.393845] [sfc efrm] nondl_register_store: cannot detect number of channels for device eth1 assuming 1
[325417.403752] [sfc efrm] efrm_nondl_register_device: register eth1
[325417.410270] [sfc efrm] eth1 type=4:0 ifindex=3
[325417.415866] [sfc efhw] xdp_set_link: eth1 does not support native XDP, using generic mode
[325417.424372] [sfc …
```
> Add capability to build/run onload-AF_XDP on aarch64 hosts

- src/driver/linux_resource/ci_arm64_insn.c
- src/driver/linux_resource/ci_arm64_insn.h
- src/driver/linux_resource/ci_arm64_patching.c
- src/driver/linux_resource/ci_arm64_patching.h
- src/driver/linux_resource/mmake.mk
- src/driver/linux_resource/syscall_aarch64.c
Fix aarch64 `sys_call_table` look up code to be compatible with modern kernels.
Tested on Raspberry Pi 4 Model B Rev 1.4 with Debian 11 with kernel versions 5.15.83, 5.10.110, 5.4.83:
```bash
sudo ./scripts/onload_install --no-sfc --no-initramfs
sudo onload_tool reload --onload-only
echo /home/pi/onload/src/tools/bpf_link_helper/bpf-link-helper | sudo tee /sys/module/sfc_resource/parameters/bpf_link_helper
echo eth0 | sudo tee /sys/module/sfc_resource/afxdp/register
echo 0 | sudo tee /sys/module/sfc_resource/parameters/enable_af_xdp_flow_filters
sudo onload nc -l -p 6666
sudo onload nc 10.0.0.2 6666
```
> Fix aarch64 sys_call_table look up code

- src/driver/linux_resource/kernel_compat.sh
- src/include/ci/driver/chrdev.h
- src/lib/transport/ip/netif_table.c
Fix the errors happening on Linux 6.2:
```
onload/src/include/ci/driver/chrdev.h:89:23: error: assignment to ‘char * (*)(const struct device *, umode_t *)’ {aka ‘char * (*)(const struct device *, short unsigned int *)’} from incompatible pointer type ‘char * (*)(struct device *, umode_t *)’ {aka ‘char * (*)(struct device *, short unsigned int *)’} [-Werror=incompatible-pointer-types]
reg->class->devnode = chrdev_devnode_set_mode;
```
and
```
build/x86_64_linux-6.2.10-1.el9.elrepo.x86_64/lib/transport/ip/netif_table.c:55: error: "__ID" redefined [-Werror]
55 | #define __ID(entry) ((entry)->__id_and_state & FILTER_TABLE_ID_MASK)
| 
In file included from ./include/linux/btf.h:10,
from ./include/linux/bpf.h:28,
from ./include/linux/filter.h:9,
from …
```
> Fix build for Linux 6.2

- src/lib/transport/ip/udp_recv.c
In man recv(2):
```
MSG_TRUNC (since Linux 2.2)
For raw (AF_PACKET), Internet datagram [...] sockets: return
the real length of the packet or datagram, even when it was
longer than the passed buffer.
```
This behavior is missing in onload prior to this patch, and onload would rather return the truncated size of the buffer, if the packet is larger than the provided buffer.
Note that TCP is unaffected by this and has a different behavior for MSG_TRUNC.
I tested with this test case:
```C
// Copyright 2022 Google LLC.
// SPDX-License-Identifier: Apache-2.0
#include <assert.h>
#include <errno.h>
#include <error.h>
#include <netinet/in.h>
#include <stddef.h>
#include <stdio.h>
#include <sys/socket.h>
int main(void) {
struct sockaddr_in6 sin = {
.sin6_family = PF_INET6,
.sin6_addr = in6addr_any, …
```
> udp_recv: Return real length if MSG_TRUNC is set in flags

- src/driver/linux_resource/kernel_compat.sh
- src/driver/linux_resource/kernel_compat_funcs.sh
grep 3.8 prints warning about egrep obsolescence. As a result a lot of warnings appear when building Onload modules.
The patch hides these warnings by replacing 'egrep' with 'grep -E'.
Fixes #151
---
Testing:
`make -C build/x86_64_linux-6.2.10-100.fc36.x86_64/ HAVE_SFC=0` does not produce warnings.
`autocompat.h` file is generated correctly.
> linux_resource/kernel_compat: replace obsolete egrep with grep -E

- src/tools/ip/tcpdump_bin.c
Onload GNU build fails on Fedora 38 with GCC 13.1.1: tcpdump_bin.c:230:11: error: ‘hwports’ may be used uninitialized [-Werror=maybe-uninitialized]
The patch fixes that error by initializing the local variable to zero.
> onload_tcpdump: fix maybe-uninitialized warning

- src/driver/linux_onload/epoll_device.c
OO_EPOLL1_IOC_BLOCK_ON ioctl handler takes reference to epoll descriptor with fget(), but does not release it, which causes kernel memory leak on Linux 6.1. So, call fput() right after using it.
Fixes #154
> epoll1: release reference to epoll fd in epoll_wait routine

- src/lib/efhw/ef10.c
Add prefixes to the filter defines to avoid potential clashes with kernel headers names and errors like this:
error: "IP_PROTOCOL" redefined [-Werror]
---
Build passes on Ubuntu 23.04 with kernel `6.3.7-060307-generic`.
Unfixed build (without the patch):
```
/home/nikitins/work/v5/build/x86_64_linux-6.3.7-060307-generic/driver/linux_resource/ef10.c:263: error: "IP_PROTOCOL" redefined [-Werror]                                                                          
263 | #define IP_PROTOCOL     (1 << MC_CMD_FILTER_OP_IN_MATCH_ETHER_TYPE_LBN |\                                                                                                                                  
| …
```
> linux_resource/ef10: make defines more unique

- src/driver/linux_resource/kernel_compat.sh
- src/include/ci/driver/chrdev.h
- src/include/ci/driver/kernel_compat.h
- src/lib/efthrm/tcp_helper_linux.c
This PR fixes modules build errors on Linux 6.4:
```
onload/src/include/ci/driver/chrdev.h: In function ‘create_chrdev_and_mknod’:
/usr/src/linux-headers-6.4.0-0-common/include/linux/export.h:27:22: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
27 | #define THIS_MODULE (&__this_module)
|                     ~^~~~~~~~~~~~~~~
|                      |
|                      struct module *
onload/src/include/ci/driver/chrdev.h:88:29: note: in expansion of macro ‘THIS_MODULE’
88 |   reg->class = class_create(THIS_MODULE, name);
|                             ^~~~~~~~~~~
```
and
```
build/x86_64_linux-6.4.0-0-amd64/driver/linux_onload/tcp_helper_linux.c:49:43: error: ‘struct iov_iter’ has no member named ‘iov’; did you mean …
```
> Fix build on Linux 6.4

- src/include/ci/driver/kernel_compat.h
- src/lib/efhw/af_xdp.c
AF_XDP rings were allocated as physically-continuous memory before linux-6.3. Now rings are vmalloc'ed.  Let's map these new rings via pin_user_pages().
**Testing:**
Socket Tester sanity tests do not show any regression when using AF_XDP Onload with Debian Testing, kernels `6.3.0-0-amd64` and `6.1.0-9-amd64`
> Handle XDP rings for linux>=6.3

- src/driver/linux/unload.sh
This will avoid the following warning messages from pkill version 4.0: "pkill: pattern that searches for process name longer than 15 characters will result in zero matches
Try `pkill -f' option to match against the complete command line."
Using the -f option in this case is unnecessary, since it implies searching for a template in the program parameters: it will kill, for example, the process 'vim onload_helper'.
-------
Checked on Deb12 and Ubu23.04 (with pkill v.4). Before this patch, the following command line shows the error:
```shell
$ sudo ./build/x86_64_linux-6.1.0-9-amd64/driver/linux/unload.sh 
pkill: pattern that searches for process name longer than 15 characters will result in zero matches
Try `pkill -f' option to match against the complete command line.
```
Note: this warning …
> unload.sh: use the exact process name to kill it

- src/driver/linux_resource/syscall_x86.c
In a clang-compiled Linux we are testing with, the syscall retpoline jump was compiled to:
```
4c 8b 1c cd 90 02 20 82     mov    -0x7ddffd70(,%rcx,8),%r11
4c 89 f7                    mov    %r14,%rdi
e8 ad 5d 3b 00              call   <x86_indirect_thunk_r11>
```
Because R11 is an x86_64 extension register, emit_indirect() gives the modified call instruction an REX.B prefix (0x41), becoming:
```
41 ff d3                    call   *%r11
66 90                       nop2
```
This patch adds a condition for such. It also allows other non-extension-registers that isn't RAX to be used, instead of hardcoding 0xd0 for RAX.
I believe in the case of X86_FEATURE_RETPOLINE_LFENCE with extension registers, the patch simply won't be performed, because lfence + call now takes 6 bytes and …
> syscall_x86: Allow non-RAX indirect jumps

- src/driver/linux_resource/kernel_compat_funcs.sh
kernel_compat_funcs performs an awk on $KBUILD_MODULE_SYMVERS even when it is empty. This causes the script to hang forever. Add a check for if $KBUILD_MODULE_SYMVERS is empty before the awk.
> linux_resource/kernel_compat_funcs: Fix hang when $KBUILD_MODULE_SYMVERS is empty

- src/driver/linux_onload/cplane.c
- src/include/ci/driver/chrdev.h
- src/include/ci/driver/eftest_kernmem.h
- src/include/ci/internal/ip_shared_types.h
- src/include/ci/tools/sysdep.h
- src/lib/efrm/efrm_pd.c
- src/tests/onload/onload_remote_monitor/internal_tests/test_ftl.c
- src/tools/onload_remote_monitor/ftl_defs.h
- src/tools/onload_remote_monitor/orm_json_lib.c
Since commit 2d47c6956ab3 ("ubsan: Tighten UBSAN_BOUNDS on GCC") in Linux-6.5 we can't use arrays of size [0] or [1] because it triggers UBSAN false-positive warnings "array-index-out-of-bounds".
Use __DECLARE_FLEX_ARRAY() macro to declare flexible arrays in those cases. For arrays with size [1] use a union to keep the size of a struct containing the flexible array unchanged.
---
Depends on #169
Checked on Ubuntu 23.10 `6.5.0-9-generic`
> driver: fix out-of-bounds UBSAN warning

- src/include/ci/internal/ip.h
- src/include/ci/internal/opts_netif_def.h
- src/lib/transport/ip/netif_init.c
- src/lib/transport/ip/tcp_rx.c
- src/lib/transport/ip/tcp_synrecv.c
- src/lib/transport/unix/tcp_fd.c
Linux and Onload handles the backlog argument of listen() function differently, starting from 4.10 (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=5ea8ea2cb7f1d0db15762c9b0bb9e7330425a071).
When number of connection requests reaches the backlog:
Linux - drops SYN
Onload - responses with SYNACK, and only then drops ACK from peer.
Two commits are proposed:
```
lib/transport: fix listen() backlog argument handling
Mimic Linux when accept queue is full - drop SYN.
See also Linux commit where the change was introduced:
5ea8ea2cb7f1d0db15762c9b0bb9e7330425a071
---
lib/transport: support somaxconn parameter
Use the /proc/sys/net/core/somaxconn value to limit accept queue
maximum size.
```
The first commit fixes the inconsistency and make Onload behave like Linux.
The …
> Fix listen() backlog handling

- src/driver/linux_onload/oo_shmbuf.c
- src/include/ci/tools/log.h
- src/include/onload/oo_shmbuf.h
- src/lib/citools/fail.c
- src/lib/citools/log_buffer.c
- src/lib/citools/sys_fail.c
Fix for the #190 
---
Tested by building both user and driver part of Onload on Fedora 38 with `6.5.6-200.fc38.x86_64`
All warnings are gone.
> Fix objtool warnings

- src/driver/linux_onload/onload_kernel_compat.h
- src/driver/linux_onload/ossock_calls.c
- src/driver/linux_resource/kernel_compat.sh
- src/lib/efhw/af_xdp.c
- src/lib/efthrm/tcp_helper_resource.c
Fix compatibility issues introduced by new Linux versions 6.6 and 6.7.
Checked on latest Debian testing (trixie) kernels - 6.6-amd64 and 6.7-amd64 (with HAVE_SFC=0)
Also checked CentOS 8 4.18.0-535.el8.x86_64.
> Fix build issues on new Linux kernels

- src/driver/linux_onload/ossock_calls.c
Fix error path in handover code, which handles the case when the file is changing under Onload's feet.  It looks like the error path was not updated when locking schema in all the oo_fd_replace_file() function was changed, and file_lock spin lock was replaced by task_lock.
> driver/onload: fix spinlock unlocking in error path

- src/driver/linux_onload/onload_kernel_compat.h
- src/driver/linux_onload/ossock_calls.c
- src/driver/linux_resource/kernel_compat.sh
Recent linux-6.7 compat patch replaced lookup_fd_rcu() with lookup_fdget_rcu(). They are not identical though, because the latter takes reference to the file.
The patch adds extra fput() and fixes the wrapper to be compatible with older kernels.
Fixes: e34a911603af ("driver: compat for lookup_fd_rcu()")
> kcompat: fix file refcounting issue in oo_fd_replace_file()

- Makefile
Pass -mno-outline-atomics for gcc>=10, like it would work with old-style driver build.
> issue #212: fix aarch64 build with newdriver

- src/driver/linux_resource/kernel_compat.sh
- src/lib/efthrm/tcp_helper_linux.c
iov_iter_is_bvec() and iov_iter_is_pipe() appeared in 4.20. Make a compat for it.
> cleanup: fix build for Debian10 4.19 kernel

- src/lib/transport/unix/epoll_fd.c
- src/lib/transport/unix/ul_epoll.h
After closing a dup()'ed epoll fd all the sockets which were added to that fd get invalid epoll reference in citp_fdinfo. In epoll3 case it leads to a refcounting issue - when the socket is closed we do not release reference to netif taken in citp_epoll_set_home_stack().
Keep list of all opened epoll fds associated with this epoll set and set valid epoll_fd to all sockets referenced to the epoll fd which is being closed.
> epoll3: fix socket cleanup after duplicating epoll fd

- scripts/onload_misc/dkms.conf
When `CC` is set, it appears to switch into cross-compile mode which breaks the DKMS build.
> Unset CC which breaks onload DKMS build

- src/include/ci/internal/ip.h
- src/lib/transport/ip/common_sockopts.c
- src/lib/transport/ip/udp_sockopts.c
Fix computing the limits for *_BUFFORCE socket options.
Take into account missing PKTS_PER_SET constant.
> lib/ip: fix {SND,RCV}BUFFORCE socket options limits

- src/include/ci/internal/ip.h
- src/lib/transport/ip/common_sockopts.c
- src/lib/transport/ip/udp_sockopts.c
Do not allow socket receive buffer size to exceed maximum number of RX packets.
> lib/ip: calculate SO_RCVBUFFORCE limit more accurately

- src/lib/transport/ip/udp_recv.c
- src/lib/transport/ip/udp_send.c
Handle address space of a data pointer in udp tx/rx kernel-variant functions. It is needed for correct data copy to/from Onload sockets with kernel API. The usecase: calling splice to/from unaccelareted pipe from/to UDP socket.
@okt-yurijp please check it out
> lib/ip: handle address space in udp tx/rx functions

- Makefile
Linux 6.10 has broken Onload kernel modules build by replacing $(src) with $(obj) in its makefiles.
See Linux commit 9a0ebe5011f49e932bb0a2cea2034fd65e6e567e
This patch implements a possible approach - create symlinks to Onload source files in build directory.
---
Possible fix for #236
Checked on CentOS 9 `6.10.5-1.el9.elrepo.x86_64` and Ubuntu 22.04 `6.8.0-40-generic` by running `make`/ `mmakebuildtree --driver && make`.
Note: there are other build issues, related to linux-6.10, which I'll address separately.
> Fix root makefile to work with linux 6.10

- Makefile
- src/driver/linux_onload/onload_kernel_compat.h
- src/driver/linux_onload/onloadfs.c
- src/driver/linux_resource/kernel_compat.sh
- src/lib/efthrm/tcp_helper_ioctl.c
- src/lib/efthrm/tcp_helper_linux.c
Fix issue #264 and couple of others related to linux-6.13.
---
Checked by running `HAVE_SFC=0 make` on a few kernels: 5.15, 6.1, 6.13.
Build and some basic tests pass.
> Fix driver build for linux 6.13

- src/include/ci/tools/sysdep.h
- src/lib/transport/ip/csum_copy_iovec_setlen.c
- src/lib/transport/ip/tcp_misc.c
- src/lib/transport/ip/tcp_tx_reformat.c
Avoid false-positive warnings like:
memcpy: detected field-spanning write (size 1436) of single field "dest" at src/lib/transport/ip/tcp_tx_reformat.c:74 (size 0)
Since actual allocation is bigger than ci_ip_pkt_fmt struct size, it is safe to copy beyond the struct.
Use unsafe_memcpy()/unsafe_memmove() for copying to ci_ip_pkt_fmt struct in a few places, which trigger the warning:
ci_tcp_tx_merge_segment(), ci_tcp_rx_pkt_coalesce() and do_copy_from_user().
> compat: avoid fortify memcpy/memmove warnings on linux>=6.11

- src/driver/linux_onload/onload_kernel_compat.h
- src/driver/linux_onload/ossock_calls.c
- src/lib/efthrm/tcp_helper_endpoint_move.c
Using Onload with Linux-6.12 results in crash with NULL pointer dereference.  It happens in many tests in Socket Tester, in nginx, in other cases.  In the git log I see that linux-6.12 support was added under ON-16108, but it definitely was not tested properly.
With these patches I see some basic tests passing on Linux-6.12.
> Fix linux-6.12 support

- src/include/ci/efhw/tph.h
This is due to the compatibility version of `pcie_tph_get_cpu_st()` always being used (`EFRM_HAVE_LINUX_TPH_H` isn't defined before including `ci/efhw/tph.h`).
Here's a one line change to include `ci/driver/kernel_compat.h` in the same fashion as in `ef10ct.c`, though maybe it's better for `ci/efhw/tph.h` to include it?
Testing: enabling steering on X2522 no longer reports EINVAL.
Regards
> TPH mode in ef10 isn't ever enabled.

- scripts/onload_build
It's missing an `export KVER` compared with the `--kernelver <VER>` path.
Before:
```sh
> uname -r
6.14.3-300.fc42.x86_64
> ./scripts/onload_build --kernel --user64 --kernelver=6.14.5-300.fc42.x86_64
...
> ll build
total 0
drwxr-x--- 1 luke luke 222 May  9 19:38 gnu_x86_64
drwxr-x--- 1 luke luke 292 May  9 19:38 x86_64_linux-6.14.3-300.fc42.x86_64
```
After:
```sh
> ./scripts/onload_build --kernel --user64 --kernelver=6.14.5-300.fc42.x86_64
...
> ll build
total 0
drwxr-x--- 1 luke luke 222 May  9 19:40 gnu_x86_64
drwxr-x--- 1 luke luke 292 May  9 19:40 x86_64_linux-6.14.5-300.fc42.x86_64
```
Thanks
> Fix --kernelver=<VER> in onload_build.
